### ISSUE TITLE
Error during project generation

### ISSUE THREAD

**Issue by MikeQuaci** [krakenjs/generator-kraken#185]
I know it won't be much to work with but i get this error after defining the  JavaScript library option:

events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: undefined is not a function
    at composeWith (/home/michael/npm/lib/node_modules/generator-kraken/node_modules/yeoman-generator/lib/base.js:620:26)
    at subGenerators (/home/michael/npm/lib/node_modules/generator-kraken/app/index.js:114:18)
    at /home/michael/npm/lib/node_modules/generator-kraken/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:367:17)

Other infos:
Node: v0.12.7
NPM: 2.11.3
yo: 1.1.2
O.S: Ubuntu 14.04 LTS

**Comment by MikeQuaci** [comment]
It was a configuration problem due the usage of NVM for handling node v0.12 & v0.10

Solution found here: https://github.com/DaftMonk/generator-angular-fullstack/issues/308
