### ISSUE TITLE
unit tests failing

### ISSUE THREAD

**Issue by grawk** [krakenjs/generator-kraken#209]
when doing a fresh install (or during travisCI), all tests fail with essentially this error:

```
0 passing (2s)
  33 failing

  1) kraken:app scaffolded application can run the build task:
     Uncaught TypeError: Cannot convert undefined or null to object
      at Function.keys (native)
      at Object.exports.mockPrompt (node_modules/yeoman-generator/lib/test/helpers.js:115:10)
      at test/util/run.js:19:17
      at node_modules/yeoman-generator/lib/test/helpers.js:96:5
      at next (node_modules/rimraf/rimraf.js:74:7)
      at FSReqWrap.CB [as oncomplete] (node_modules/rimraf/rimraf.js:110:9)

...
```

**Comment by grawk** [comment]
Resolved via https://github.com/krakenjs/generator-kraken/pull/208 (pending)
